### ISSUE TITLE
scroll down to bottom of list of colored tags

### ISSUE THREAD

**Issue by st0rmchaser** [Piwigo/Piwigo-Colored-Tags#1]
I have an issue but do not know if this is a Piwigo issue or a colored tag issue because I came across this plugin and installed it the same day I installed Piwigo.  

issue:  When selecting colored tags from a list I can't scroll to the bottom of the list to select the tags.  If I use the browser scroll to move pointer so I can scroll down then the tags list is not active and I lose my place trying to scroll.  The browser jumps up a tad bit and I can't get my full list of tags.  This is not an issue that just started with the new Piwigo, I started using Piwigo 2.7.2 it was a issue from the beginning.  Just now had the time to post this.  See the image and note I can't scroll down. 
![color-tags](https://cloud.githubusercontent.com/assets/10674549/5880542/55363b08-a307-11e4-8bfe-0a6325d7071a.jpg)

**Comment by mistic100** [comment]
not a plugin bug, more related to selectize and how it is used in Piwigo
see brianreavis/selectize.js#437
